import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/layout/Header";

const geistSans = localFont({
  src: "./fonts/Roboto/Roboto-Black.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Roboto/Roboto-BoldItalic.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-w-6xl mx-auto p-4">
        <Header />
        {children}
        <footer className="border-t p-8 mt-16 text-center
        text-gray-500">
          &copy; 2023 All rights reserved
        </footer>
        </main>
      </body>
    </html>
  );
}
